language: scala
jdk:
  - oraclejdk8
before_script: ./make_credentials.sh
script: 
  - sbt test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# If building master, Publish to Sonatype
after_success: "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && sbt publish"

sudo: false

# Cache settings
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

# whitelist
branches:
  only:
    - master
